### ISSUE TITLE
AMS integration broken after installing core-24.3.0

### ISSUE THREAD

**Issue by BrukerJan** [turbokongen/hass-AMS#101]
Refering to issue #113275.

I reported the matter as a core bug, but it has been closed with reference to the fact that the bug occurs in the AMS integration and must be reported to the maintainer of that integration.

**Comment by turbokongen** [comment]
Duplicate of #100

**Comment by BrukerJan** [comment]
Problem solved, at least in my setup - thank you for taking action!
