### ISSUE TITLE
Missing attribute when using Kaifa one ohase meter

### ISSUE THREAD

**Issue by jorgen666** [turbokongen/hass-AMS#17]
I'm getting readings on all attributes except ams_active_power_import. This one doesn't show up in the version 1.04 on HA 0.107.7
I have Kaifa one phase meter.

**Comment by turbokongen** [comment]
Could you please enable debug, and paste the log for about one minute?

**Comment by jorgen666** [comment]
Yes I will, I just making a fresh install just to see if this gone bad in other ways

**Comment by turbokongen** [comment]
I suspect mayde the unique_id change will make for a complete reinstall.
Meaning:
- Delete the integration
- Restart homeassistant
- Add the integration
See if that makes a change

**Comment by jorgen666** [comment]
Ok, Jeg har reinstallert hele denne HA instansen. Er en av slave instansene. Så får man se

**Comment by jorgen666** [comment]
Nå har jeg bygd opp denne maskinen i fra bunnen igjen, og får frem alle attributter untatt ams_active_power_  alle andre variabler blir lest av korregt

**Comment by jorgen666** [comment]
HHer er loggen etter litt kjøring på denne 
[log ams.txt](https://github.com/turbokongen/hass-AMS/files/4411420/log.ams.txt)

**Comment by jorgen666** [comment]
Hei

Jeg gikk tilbake til versjon 1.02 den fungerer korrekt med den strømmåleren jeg har.

**Comment by turbokongen** [comment]
Kan du prøve: https://github.com/turbokongen/hass-AMS/tree/bugfix104
Jeg hadde brukt feil sensornavn for å få alle attributtene.

**Comment by jorgen666** [comment]
Denne varianten førte ikke til noen endring i forhold til 1.04. Men kan ta å sammenligne den med den fungerende versjon 1.02

**Comment by turbokongen** [comment]
Ok. Da funker det ikke å få alle attributes med kaifa som med aidon.
Pusher v1.05 senere idag.
