### ISSUE TITLE
Cpu usage

### ISSUE THREAD

**Issue by Hellowlol** [turbokongen/hass-AMS#2]
The cpu usage is very high (I have a solution for this pr is coming)

I have added a async method and threaded method, I don't know what is best yet.

**Comment by turbokongen** [comment]
Yes, I did notice that. Initially I wanted to use the async serial, but I could not get it to work. Looking forward for your PR.

**Comment by thomasja27** [comment]
The same thing happens to me, the load on the CPU increases to 30% when the plugin is active. usually I am at 1-2%

**Comment by turbokongen** [comment]
could you please try the https://github.com/turbokongen/hass-AMS/tree/cpu_ branch to see if that changes anything?

**Comment by Hellowlol** [comment]
I noticed the same issue on my rpi3 and nuc i5

**Comment by turbokongen** [comment]
Does the cpu_ branch change the behaviour? I got 5-10% less Cpu usage on my server, and 1-4% less on the rpi3+

**Comment by Hellowlol** [comment]
Dunno, im using the stuff branch. Ill try the cpu_ later.

**Comment by thomasja27** [comment]
With the cpu_ branch load is around 2-3% so it did make a huge difference :) The load was around 30% before.

My system:
Lenovo M92P
Intel Core I3-2120T @ 2.6 GHz
6 GB Ram
256GB SSD

**Comment by turbokongen** [comment]
Perfect! thanks for the feedback.
