### ISSUE TITLE
No sensors after restart

### ISSUE THREAD

**Issue by jgallis** [turbokongen/hass-AMS#21]
Running Home Assistant 0.107.7 on VM,with Aidon 6525 meter and have this USB dongel https://www.aliexpress.com/item/32719562958.html
After first install the intergration works perfect, but after restart there are no sensors showing. Need to remove the intergration, take a new restart, and add the intergration again. 

This is how the intergration looks after restart: 
![Screen Shot 04-05-20 at 09 30 AM](https://user-images.githubusercontent.com/43672698/78506588-e7639500-777a-11ea-8e3d-f94cb08cc857.JPG)

It looks like the sensors are there when I open the intergration: 
![Screen Shot 04-05-20 at 09 31 AM](https://user-images.githubusercontent.com/43672698/78506604-ff3b1900-777a-11ea-8a22-c1edb74a6df5.JPG)

But no sensors in lovelace UI:
![Screen Shot 04-05-20 at 09 37 AM 001](https://user-images.githubusercontent.com/43672698/78506612-0bbf7180-777b-11ea-990e-cf163e5146f9.JPG)

This is the setup: 
![Screen Shot 04-05-20 at 09 37 AM](https://user-images.githubusercontent.com/43672698/78506621-20036e80-777b-11ea-80b3-4f80d4e98c83.JPG)

Have set the logs to debug and after restart it looks like the data is recived, but its not working. Can send you the logs if you want.

**Comment by Hellowlol** [comment]
Seems similar to https://github.com/turbokongen/hass-AMS/issues/18

**Comment by turbokongen** [comment]
Fixed in release v1.06
