### ISSUE TITLE
Unit of measurement - minor bug

### ISSUE THREAD

**Issue by jnrksv** [turbokongen/hass-AMS#35]
Sorry, I saw this a long time ago, but it slipped my mind.
There's a minor bug in the unit_of_measurement for reactive_power_export and reactive_power_import. I think the measured unit is VAr not kVAr.

![hass_ams](https://user-images.githubusercontent.com/24974747/94991937-b677e780-0586-11eb-8cf1-2d092e2f65c5.png)

**Comment by turbokongen** [comment]
Thanks for reporting. 👍
