### ISSUE TITLE
Make values available in the new energy integration.

### ISSUE THREAD

**Issue by bthovda** [turbokongen/hass-AMS#49]
https://www.home-assistant.io/more-info/statistics/

**Comment by turbokongen** [comment]
I have started to implement this.

**Comment by pinetreecabin** [comment]
> I have started to implement this.

Thank you!!

**Comment by turbokongen** [comment]
You can track the progress here: https://github.com/turbokongen/hass-AMS/pull/50
If you want to test before publish, use this branch: https://github.com/turbokongen/hass-AMS/tree/energy_dashboard

**Comment by turbokongen** [comment]
Fixed by https://github.com/turbokongen/hass-AMS/pull/50
