### ISSUE TITLE
Missing meter type

### ISSUE THREAD

**Issue by oeriksen** [turbokongen/hass-AMS#56]
I installed this today but initially it failed because my meter was missing from the METER_TYPE array in const.py
Here is an excerpt from the log: [home-assistant.log](https://github.com/turbokongen/hass-AMS/files/7288064/home-assistant.log)
After adding `6841128: "Omnipower 3 Phase meter"` ([const.py.txt](https://github.com/turbokongen/hass-AMS/files/7288095/const.py.txt)) it worked great (thank you by the way!).
Here is a picture of the meter if you want a better description:

![kamstrup_6841128](https://user-images.githubusercontent.com/25210491/136073574-358da170-bb24-4199-8867-68ded0b50a73.jpg)

**Comment by turbokongen** [comment]
Thanks for reporting this. Your meter has been added to v1.7.1 and an additional safeguard is put in place to handle unknown meters in the future. 👍
