### ISSUE TITLE
Unknown unit

### ISSUE THREAD

**Issue by oeriksen** [turbokongen/hass-AMS#58]
I know this is really the wrong place but I'm curious if I'm the only one getting the messages below. I've searched and I can't find anyone else reporting this. Had to lookup kVAr, never heard about that before (neither reactive energy).

WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.ams_reactive_energy_export_57**42 has unknown unit kVAr

WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.ams_reactive_energy_import_57**42 has unknown unit kVAr

**Comment by oeriksen** [comment]
I switched to the v1.7.2 branch. I'm still getting the warning messages. But I don't get any other (new) errors so the branch is stable/safe and that's something :smiley: 
As far as I can understand from the changes you did you limited total increasing state class to the active energy sensors (which removes it from the reactive sensors). So I might have to remove the integration and add it back again for that change to be in effect?
I also checked [sensor.recorder](https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/recorder.py) and it reads from the database, when generating long term statistics, where also total increasing state class is stored. So I might need to edit that as well. A quick update query should fix that.
If you agree to my thoughts I'll try to do this tomorrow night, it's getting to late now.

**Comment by turbokongen** [comment]
I have uploaded some more changes to the branch. please test.
This should remove unknown state class None also.

**Comment by oeriksen** [comment]
Now I'm getting a new warning: Found unexpected state_class None for sensor.ams_active_energy_import_57**42

**Comment by oeriksen** [comment]
By the way, I see you have a typo in the new (my) Kamstrup meter type. You have written 6851128 but it is 6841128.
