### ISSUE TITLE
minor spelling in swedish translation

### ISSUE THREAD

**Issue by enpontus** [turbokongen/hass-AMS#65]
i think this is slightly better swedish imho (not perfect but a step in the right direction) some spelling and wording changes...

{
    "config": {
        "abort": {
           "single_instance_allowed": "Endast en instans av AMS läsaren är tillåten"
        },
        "title": "AMS Reader",
        "step": {
            "user": {
                "title": "AMS läsare",
                "description": "Installera sensor för AMS läsare",
                "data": {
                    "serial_port": "Serieport",
                    "parity": "Paritet",
                    "meter_manufacturer": "Mätartillverkare",
                    "baudrate": "Baudrate"
                }
            }
        },
        "error": {
            "name_exists": "Namn finns"
        }
    }
}

**Comment by turbokongen** [comment]
Thank you for the fix.
Fixed in v1.8.2
