### ISSUE TITLE
Hydrocal M3 integrations

### ISSUE THREAD

**Issue by r-zlotorzynski** [turbokongen/hass-AMS#69]
Hello

Would it be possible to integrate it with a Hydrocal M3 heat meter?
![img](https://user-images.githubusercontent.com/26817418/146989737-686411e8-7802-4c99-85dc-4cbb86791487.jpg)

[https://bmeters.pl/pl/hydrocal_m3/410/](url)

Below I present the possible parameters for reading.
![Zrzut ekranu 2021-10-24 041817](https://user-images.githubusercontent.com/26817418/146990508-4081d42e-1e49-4c06-91de-f9e6af787628.jpeg)

**Comment by turbokongen** [comment]
This component will only be supporting the reading of the Scandinavian AMS standard.
Sorry.
