### ISSUE TITLE
User input malformed: value must be one of [] for dictionary value @ data['serial_port']

### ISSUE THREAD

**Issue by kayt00re** [turbokongen/hass-AMS#79]
I am trying to add the integration and get this message. What should i do or not do? :) 

I have chose Serialport, kamstrup, parity E and baud 2400

**Comment by turbokongen** [comment]
above the choices of meter manufacturer, parity and baudrate you should select the serial port to use. If there are none, the system has not detected the USB serial controller. 

![image](https://user-images.githubusercontent.com/16622752/190484763-d650d3b2-9493-46ec-a072-fa9c27b92874.png)
